# Generated by Django 6.0 on 2025-12-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.URLField()),
                ('publicado_em', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
