# Generated by Django 6.0 on 2025-12-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIrest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_informe',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
