# Generated by Django 6.0 on 2025-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIrest', '0002_alter_news_informe_publicado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_informe',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
