# Generated by Django 6.0 on 2026-01-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIrest', '0003_alter_news_informe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_informe',
            name='portal',
            field=models.CharField(default='desconhecido', max_length=20),
        ),
    ]
