# Generated by Django 6.0 on 2026-01-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIrest', '0004_news_informe_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_informe',
            name='titulo',
            field=models.CharField(),
        ),
    ]
