# Generated by Django 6.0 on 2026-01-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIrest', '0005_alter_news_informe_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_informe',
            name='titulo',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='news_informe',
            name='url',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
