# Generated by Django 6.0 on 2026-01-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIrest', '0006_alter_news_informe_titulo_alter_news_informe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_informe',
            name='url',
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
