# Generated by Django 6.0 on 2026-01-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIrest', '0007_alter_news_informe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_informe',
            name='imagem',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='news_informe',
            name='url',
            field=models.URLField(max_length=400, unique=True),
        ),
    ]
